controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

recherche:
    path: /recherche
    controller: App\Controller\AssociationController::recherche
    methods: ['POST']

dql:
    path: /dql
    controller: App\Controller\DonationController::dql
    methods: ['POST']

name:
    path: /add_association
    controller: App\Controller\AssociationController::addAssociation
    methods: ['POST']

 