controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

front:
    path: /front
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'baseFront.html.twig'

back:
    path: /back
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
        template: 'baseBack.html.twig'

complaint_index:
    path: '/complaints'
    controller: App\Controller\ComplaintController::index

response_index:
    path: '/responses'
    controller: App\Controller\ResponseController::index

complaints_by_user:
    path: /usercomplaint/{userId}
    controller: App\Controller\ComplaintController::user_index

reponses_by_user:
    path: /userreponse/{userId}
    controller: App\Controller\ComplaintController::reponsesByUser